defmodule Eulixir.Problem002 do
  @moduledoc """
    http://projecteuler.net/problem=2
    Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. By starting with 1 and 2, the first 10 terms will be:
      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.
  """

  require Integer

  @doc """
    iex> Eulixir.Problem002.solve(80)
    44
  """
  def solve(limit) do
    fib(0, 1, 0, limit)
  end

  defp fib(_, b, acc, limit) when b >= limit, do: acc

  defp fib(a, b, acc, limit) do
    sum = a + b
    new_acc = acc + (if Integer.is_even(sum), do: sum, else: 0)
    fib(b, sum, new_acc, limit)
  end

  def solution do
    solve(4_000_000)
  end
end

